# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCpoLtst6bKSvOMDvgBymWBPItCGo2s9
"""

import pandas as pd
baza={
      "FISH":["Isoqjanov Muhammadrizo","Zaynobiddinov Shohruh","Rasulov Omadbek","Atajanova Muazzam","Tursunov Ikromjon"],
      "YOShI":["19","19","20","20","18"],
      "JINSI":["Ogil bola","Ogil bola","Ogil bola","Qiz bola","Ogil bola"],
      "Maktab raqami":["40","50","20","21","6"],
}
df=pd.DataFrame(baza)
print(df)

filtr=df.loc[df["JINSI"]=="Ogil bola"]
print(filtr)

